openapi: 3.0.3
info:
  title: API.Rasp.Yandex.Net
  description: API Яндекс.Расписаний
  version: 3.0.0

servers:
  - url: https://api.rasp.yandex-net.ru

tags:
  - name: nearestStations
    description: Список ближайших станций
  - name: scheduleOnStation
    description: Расписание на станции
  - name: thread
    description: Список станций следования нитки

paths:
  #############################
  # 1) nearest_stations
  #############################
  /v3.0/nearest_stations/:
    get:
      tags: [nearestStations]
      summary: Список ближайших станций
      operationId: getNearestStations
      parameters:
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: lat
          in: query
          required: true
          schema:
            type: number
        - name: lng
          in: query
          required: true
          schema:
            type: number
        - name: distance
          in: query
          required: true
          schema:
            type: integer
        - name: format
          in: query
          required: false
          schema:
            type: string
        - name: lang
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stations'

  #############################
  # 2) schedule_on_station
  #############################
  /v3.0/schedule/:
    get:
      tags: [scheduleOnStation]
      summary: Расписание на станции
      operationId: getScheduleOnStation
      parameters:
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: station
          in: query
          required: true
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
        - name: transport_types
          in: query
          required: false
          schema:
            type: string
        - name: event
          in: query
          required: false
          schema:
            type: string
        - name: system
          in: query
          required: false
          schema:
            type: string
        - name: show_systems
          in: query
          required: false
          schema:
            type: string
        - name: direction
          in: query
          required: false
          schema:
            type: string
        - name: result_timezone
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleOnStationResponse'

  #############################
  # 3) thread
  #############################
  /v3.0/thread/:
    get:
      tags: [thread]
      summary: Список станций следования нитки
      operationId: getThread
      parameters:
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: uid
          in: query
          required: true
          schema:
            type: string
        - name: from
          in: query
          required: false
          schema:
            type: string
        - name: to
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
        - name: format
          in: query
          required: false
          schema:
            type: string
        - name: lang
          in: query
          required: false
          schema:
            type: string
        - name: show_systems
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadResponse'

components:
  schemas:
    # --- Схемы для ближайших станций ---
    Stations:
      type: object
      additionalProperties: true
    Station:
      type: object
      additionalProperties: true
    Pagination:
      type: object
      additionalProperties: true
    Schedule:
      type: object
      additionalProperties: true

    # --- Схемы для расписания на станции ---
    ScheduleOnStationResponse:
      type: object
      additionalProperties: true

    # --- Схемы для ThreadService ---
    ThreadResponse:
      type: object
      additionalProperties: true
